//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMMC_Core.FileDeleteServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFileResult", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibraryTest")]
    [System.SerializableAttribute()]
    public partial class DeleteFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeleteSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleteSuccess {
            get {
                return this.IsDeleteSuccessField;
            }
            set {
                if ((this.IsDeleteSuccessField.Equals(value) != true)) {
                    this.IsDeleteSuccessField = value;
                    this.RaisePropertyChanged("IsDeleteSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileDeleteServiceReference.IFileDeleteService")]
    public interface IFileDeleteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileDeleteService/DeleteFile", ReplyAction="http://tempuri.org/IFileDeleteService/DeleteFileResponse")]
        VMMC_Core.FileDeleteServiceReference.DeleteFileResult DeleteFile(int fileId, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileDeleteService/DeleteFile", ReplyAction="http://tempuri.org/IFileDeleteService/DeleteFileResponse")]
        System.Threading.Tasks.Task<VMMC_Core.FileDeleteServiceReference.DeleteFileResult> DeleteFileAsync(int fileId, string projectName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileDeleteServiceChannel : VMMC_Core.FileDeleteServiceReference.IFileDeleteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileDeleteServiceClient : System.ServiceModel.ClientBase<VMMC_Core.FileDeleteServiceReference.IFileDeleteService>, VMMC_Core.FileDeleteServiceReference.IFileDeleteService {
        
        public FileDeleteServiceClient() {
        }
        
        public FileDeleteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileDeleteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDeleteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDeleteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VMMC_Core.FileDeleteServiceReference.DeleteFileResult DeleteFile(int fileId, string projectName) {
            return base.Channel.DeleteFile(fileId, projectName);
        }
        
        public System.Threading.Tasks.Task<VMMC_Core.FileDeleteServiceReference.DeleteFileResult> DeleteFileAsync(int fileId, string projectName) {
            return base.Channel.DeleteFileAsync(fileId, projectName);
        }
    }
}
