//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMMC_Core.FileLoaderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadFileInput", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibraryTest")]
    [System.SerializableAttribute()]
    public partial class LoadFileInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.FileInfo FileInfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RepositoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RevisionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.FileInfo FileInf {
            get {
                return this.FileInfField;
            }
            set {
                if ((object.ReferenceEquals(this.FileInfField, value) != true)) {
                    this.FileInfField = value;
                    this.RaisePropertyChanged("FileInf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepositoryId {
            get {
                return this.RepositoryIdField;
            }
            set {
                if ((this.RepositoryIdField.Equals(value) != true)) {
                    this.RepositoryIdField = value;
                    this.RaisePropertyChanged("RepositoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RevisionId {
            get {
                return this.RevisionIdField;
            }
            set {
                if ((this.RevisionIdField.Equals(value) != true)) {
                    this.RevisionIdField = value;
                    this.RaisePropertyChanged("RevisionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadFileResult", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibraryTest")]
    [System.SerializableAttribute()]
    public partial class LoadFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSavedSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoragePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSavedSuccess {
            get {
                return this.IsSavedSuccessField;
            }
            set {
                if ((this.IsSavedSuccessField.Equals(value) != true)) {
                    this.IsSavedSuccessField = value;
                    this.RaisePropertyChanged("IsSavedSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoragePath {
            get {
                return this.StoragePathField;
            }
            set {
                if ((object.ReferenceEquals(this.StoragePathField, value) != true)) {
                    this.StoragePathField = value;
                    this.RaisePropertyChanged("StoragePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileLoaderServiceReference.IFileLoaderService")]
    public interface IFileLoaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileLoaderService/LoadFile", ReplyAction="http://tempuri.org/IFileLoaderService/LoadFileResponse")]
        VMMC_Core.FileLoaderServiceReference.LoadFileResult LoadFile(VMMC_Core.FileLoaderServiceReference.LoadFileInput inputData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileLoaderService/LoadFile", ReplyAction="http://tempuri.org/IFileLoaderService/LoadFileResponse")]
        System.Threading.Tasks.Task<VMMC_Core.FileLoaderServiceReference.LoadFileResult> LoadFileAsync(VMMC_Core.FileLoaderServiceReference.LoadFileInput inputData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileLoaderServiceChannel : VMMC_Core.FileLoaderServiceReference.IFileLoaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileLoaderServiceClient : System.ServiceModel.ClientBase<VMMC_Core.FileLoaderServiceReference.IFileLoaderService>, VMMC_Core.FileLoaderServiceReference.IFileLoaderService {
        
        public FileLoaderServiceClient() {
        }
        
        public FileLoaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileLoaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileLoaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileLoaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VMMC_Core.FileLoaderServiceReference.LoadFileResult LoadFile(VMMC_Core.FileLoaderServiceReference.LoadFileInput inputData) {
            return base.Channel.LoadFile(inputData);
        }
        
        public System.Threading.Tasks.Task<VMMC_Core.FileLoaderServiceReference.LoadFileResult> LoadFileAsync(VMMC_Core.FileLoaderServiceReference.LoadFileInput inputData) {
            return base.Channel.LoadFileAsync(inputData);
        }
    }
}
