//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMMC_Client.FileDeleteServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileDeleteServiceReference.IFileDeleteService")]
    public interface IFileDeleteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileDeleteService/DeleteFile", ReplyAction="http://tempuri.org/IFileDeleteService/DeleteFileResponse")]
        VMMC_Core.FileDeleteServiceReference.DeleteFileResult DeleteFile(int fileId, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileDeleteService/DeleteFile", ReplyAction="http://tempuri.org/IFileDeleteService/DeleteFileResponse")]
        System.Threading.Tasks.Task<VMMC_Core.FileDeleteServiceReference.DeleteFileResult> DeleteFileAsync(int fileId, string projectName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileDeleteServiceChannel : VMMC_Client.FileDeleteServiceReference.IFileDeleteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileDeleteServiceClient : System.ServiceModel.ClientBase<VMMC_Client.FileDeleteServiceReference.IFileDeleteService>, VMMC_Client.FileDeleteServiceReference.IFileDeleteService {
        
        public FileDeleteServiceClient() {
        }
        
        public FileDeleteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileDeleteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDeleteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDeleteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VMMC_Core.FileDeleteServiceReference.DeleteFileResult DeleteFile(int fileId, string projectName) {
            return base.Channel.DeleteFile(fileId, projectName);
        }
        
        public System.Threading.Tasks.Task<VMMC_Core.FileDeleteServiceReference.DeleteFileResult> DeleteFileAsync(int fileId, string projectName) {
            return base.Channel.DeleteFileAsync(fileId, projectName);
        }
    }
}
