//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMMC_Login.FileGetterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileGetterService.IFileGetterService")]
    public interface IFileGetterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileGetterService/GetFile", ReplyAction="http://tempuri.org/IFileGetterService/GetFileResponse")]
        VMMC_Core.FileGetterServiceReference.GetFileResult GetFile(int fileId, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileGetterService/GetFile", ReplyAction="http://tempuri.org/IFileGetterService/GetFileResponse")]
        System.Threading.Tasks.Task<VMMC_Core.FileGetterServiceReference.GetFileResult> GetFileAsync(int fileId, string projectName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileGetterServiceChannel : VMMC_Login.FileGetterService.IFileGetterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileGetterServiceClient : System.ServiceModel.ClientBase<VMMC_Login.FileGetterService.IFileGetterService>, VMMC_Login.FileGetterService.IFileGetterService {
        
        public FileGetterServiceClient() {
        }
        
        public FileGetterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileGetterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileGetterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileGetterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VMMC_Core.FileGetterServiceReference.GetFileResult GetFile(int fileId, string projectName) {
            return base.Channel.GetFile(fileId, projectName);
        }
        
        public System.Threading.Tasks.Task<VMMC_Core.FileGetterServiceReference.GetFileResult> GetFileAsync(int fileId, string projectName) {
            return base.Channel.GetFileAsync(fileId, projectName);
        }
    }
}
